# -*- coding: utf-8 -*-


AFFICHAGE_DAME = "D"
AFFICHAGE_PION = "P"
AFFICHAGE_VIDE = " "
AFFICHAGE_MOUVEMENT_POSSIBLE = "X"

COULEUR_NORD = "#0ff"
COULEUR_SUD = "#f00"
COULEUR_DEFAUT = "#000"

COULEUR_DAMIER1 = "#000"
COULEUR_DAMIER2 = "#fff"
COULEUR_MOUVEMENT_POSSIBLE = "#666"